/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.List;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import model.AgentModel;
import model.AgentSave;

/**
 *
 * @author dam2_alu10@inf.ald
 */
public class AgentJDialog extends javax.swing.JDialog {
    private AgentSave save;
    private DefaultListModel<String> listModel;
    
    /**
     * Creates new form agentesJDialog
     */
    public AgentJDialog(java.awt.Frame parent, boolean modal, AgentSave save) {
        super(parent, modal);
        this.save = save;
        initComponents();
        listModel = new DefaultListModel<>();
        agentsJList.setModel(listModel);
        cargarAgentes();
    }
    
    private void cargarAgentes(){
        if(save != null && save.getAgentes() != null){
            for(AgentModel agent : save.getAgentes()){
                String datos = agent.getNombre() + " (ID: " + agent.getId() + ") - Saldo: " + agent.getSaldo() + "€";
                listModel.addElement(datos);
            }
        }
    }
    
    public void agregarAgenteAList(String id, String nombre, double saldo){
        String item = nombre + " (ID: " + id + ") - Saldo: " + saldo + "€";
        listModel.addElement(item);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agentesJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        priceInicialJLabel = new javax.swing.JLabel();
        idJLabel = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        priceInicialJTextField = new javax.swing.JTextField();
        idJTextField = new javax.swing.JTextField();
        saveJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        agentsJList = new javax.swing.JList<>();
        listaAgentesJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        agentesJLabel.setText("Agentes");

        nameJLabel.setText("Nombre:");

        priceInicialJLabel.setText("Saldo inicial:");

        idJLabel.setText("ID:");

        saveJButton.setText("Guardar");

        cancelJButton.setText("Cancelar");

        jScrollPane1.setViewportView(agentsJList);

        listaAgentesJLabel.setText("Lista Agentes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(listaAgentesJLabel)
                        .addGap(193, 193, 193))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveJButton)
                            .addComponent(idJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceInicialJLabel))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameJTextField)
                                    .addComponent(priceInicialJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                            .addComponent(cancelJButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(agentesJLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agentesJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(listaAgentesJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idJLabel)
                            .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameJLabel)
                            .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceInicialJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceInicialJLabel)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveJButton)
                    .addComponent(cancelJButton))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setSaveJButton(ActionListener al) {
        this.saveJButton.addActionListener(al);
    }

    public void setCancelJButton(ActionListener al) {
        this.cancelJButton.addActionListener(al);
    }

    public String getIdTextField() {
        return idJTextField.getText();
    }

    public void setIdTextFiedl(String id) {
        this.idJTextField.setText(id);
    }

    public String getNameJTextField() {
        return nameJTextField.getText();
    }

    public void setNameJTextField(String nombre) {
        this.nameJTextField.setText(nombre);
    }

    public double getPriceInicial() {
        return Double.parseDouble(priceInicialJTextField.getText());
    }

    public void setPriceInicial(Double saldoInicial) {
        this.priceInicialJTextField.setText(saldoInicial.toString());
    }

    public void addGuardarJButtonActionListener(ActionListener al){
        this.saveJButton.addActionListener(al);
    }
    
    public void addCancelarJButtonActionListener(ActionListener al){
        this.cancelJButton.addActionListener(al);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agentesJLabel;
    private javax.swing.JList<String> agentsJList;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JTextField idJTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel listaAgentesJLabel;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JLabel priceInicialJLabel;
    private javax.swing.JTextField priceInicialJTextField;
    private javax.swing.JButton saveJButton;
    // End of variables declaration//GEN-END:variables
}
