/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author dam2_alu10@inf.ald
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graficJPanel = new javax.swing.JPanel();
        MenuBar = new javax.swing.JMenuBar();
        opcionesBrokerJMenu = new javax.swing.JMenu();
        gestionAgentesJMenuItem = new javax.swing.JMenuItem();
        gestionCompraVentaJMenuItem = new javax.swing.JMenuItem();
        quitJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout graficJPanelLayout = new javax.swing.GroupLayout(graficJPanel);
        graficJPanel.setLayout(graficJPanelLayout);
        graficJPanelLayout.setHorizontalGroup(
            graficJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        graficJPanelLayout.setVerticalGroup(
            graficJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        opcionesBrokerJMenu.setText("Broker");

        gestionAgentesJMenuItem.setText("Gestión de agentes");
        opcionesBrokerJMenu.add(gestionAgentesJMenuItem);

        gestionCompraVentaJMenuItem.setText("Gestión operaciones de compra y venta");
        opcionesBrokerJMenu.add(gestionCompraVentaJMenuItem);

        quitJMenuItem.setText("Salir");
        opcionesBrokerJMenu.add(quitJMenuItem);

        MenuBar.add(opcionesBrokerJMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graficJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graficJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setQuitJMenu(ActionListener al){
        this.quitJMenuItem.addActionListener(al);
    }
    
    public void setGestionAgentesJMenu(ActionListener al){
        this.gestionAgentesJMenuItem.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem gestionAgentesJMenuItem;
    private javax.swing.JMenuItem gestionCompraVentaJMenuItem;
    private javax.swing.JPanel graficJPanel;
    private javax.swing.JMenu opcionesBrokerJMenu;
    private javax.swing.JMenuItem quitJMenuItem;
    // End of variables declaration//GEN-END:variables
}
