/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;

/**
 * Clase para la vista de las operaciones
 *
 * @author dam2_alu10@inf.ald
 */
public class OperationJDialog extends javax.swing.JDialog {

    /**
     * Contructor
     *
     * @param parent
     */
    public OperationJDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        agentJComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tipoOperacionJComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        precioLimiteJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cantidadJTextField = new javax.swing.JTextField();
        guardarJButton = new javax.swing.JButton();
        cancelarJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Operation");

        jLabel2.setText("Agente:");

        jLabel3.setText("Tipo Operacion: ");

        jLabel4.setText("Precio:");

        jLabel5.setText("Cantidad:");

        guardarJButton.setText("Guardar");

        cancelarJButton.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(agentJComboBox, 0, 196, Short.MAX_VALUE)
                            .addComponent(tipoOperacionJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(precioLimiteJTextField)
                            .addComponent(cantidadJTextField))))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(guardarJButton)
                .addGap(18, 18, 18)
                .addComponent(cancelarJButton)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(agentJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tipoOperacionJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(precioLimiteJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cantidadJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarJButton)
                    .addComponent(cancelarJButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Get que devuelve el agente seleccionado
     *
     * @return
     */
    public String getAgentJComboBox() {
        return agentJComboBox.getSelectedItem().toString();
    }

    /**
     * Set donde se añade un agente al ComboBox
     *
     * @param item
     */
    public void setAgentJComboBox(String item) {
        this.agentJComboBox.addItem(item);
    }

    /**
     * Get que devuelve el tipo de operación seleccionado
     *
     * @return
     */
    public String getTipoOperacionJComboBox() {
        return tipoOperacionJComboBox.getSelectedItem().toString();
    }

    /**
     * Set donde se añade un tipo de operación al ComboBox
     *
     * @param item
     */
    public void setTipoOperacionJComboBox(String item) {
        this.tipoOperacionJComboBox.addItem(item);
    }

    /**
     * Get que devuelve el precio límite introducido
     *
     * @return
     */
    public double getPrecioLimiteJTextField() {
        return Double.parseDouble(this.precioLimiteJTextField.getText());
    }

    /**
     * Set donde se establece el precio límite
     *
     * @param precio
     */
    public void setPrecioLimiteJTextField(double precio) {
        this.precioLimiteJTextField.setText(Double.toString(precio));
    }

    /**
     * Get que devuelve la cantidad introducida
     *
     * @return
     */
    public double getCantidadJTextField() {
        return Double.parseDouble(this.cantidadJTextField.getText());
    }

    /**
     * Set donde se establece la cantidad
     *
     * @param cantidad
     */
    public void setCantidadJTextField(double cantidad) {
        this.cantidadJTextField.setText(Double.toString(cantidad));
    }

    /**
     * Método para añadir ActionListener al botón Guardar
     *
     * @param al
     */
    public void addGuardarJButtonActionListener(ActionListener al) {
        this.guardarJButton.addActionListener(al);
    }

    /**
     * Método para añadir ActionListener al botón Cancelar
     *
     * @param al
     */
    public void addCancelarJButtonActionListener(ActionListener al) {
        this.cancelarJButton.addActionListener(al);
    }

    /**
     * Get que devuelve el ComboBox de agentes
     *
     * @return
     */
    public JComboBox<String> getAgentsJCombobox() {
        return this.agentJComboBox;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> agentJComboBox;
    private javax.swing.JButton cancelarJButton;
    private javax.swing.JTextField cantidadJTextField;
    private javax.swing.JButton guardarJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField precioLimiteJTextField;
    private javax.swing.JComboBox<String> tipoOperacionJComboBox;
    // End of variables declaration//GEN-END:variables
}
